# https://github.com/pages-themes/cayman
# theme: jekyll-theme-cayman
theme: minimal-mistakes-jekyll
title: Golang
description: imti Go language development notes and best practices.
google_analytics: UA-78786435-1
