# https://github.com/pages-themes/cayman
# theme: jekyll-theme-cayman
remote_theme: "mmistakes/minimal-mistakes"
title: Golang
description: imti Go language development notes and best practices.
google_analytics: UA-78786435-1
